---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: predix
    service-cluster: load-balancer
    service: pgadmin
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    nodePort: 30020
  selector:
    app: predix
    service-cluster: load-balancer
    service: pgadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: predix
    service-cluster: load-balancer
    service: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predix
      service-cluster: load-balancer
      service: pgadmin
  template:
    metadata:
      labels:
        app: predix
        service-cluster: load-balancer
        service: pgadmin
    spec:
      containers:
      - name: load-balancer-pgadmin
        image: dpage/pgadmin4
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: nobody@example.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: pg@admin4
        ports:
        - containerPort: 80

