#% text_encoding = iso8859_1

:tool_name			:en_gb		Database Compression
:hot				:en_gb		Hot
:online				:en_gb		Online
:source_path			:en_gb		Source Path
:source_folder_browse		:en_gb		Browse
:dest_path			:en_gb		Destination Path
:destination_folder_browse	:en_gb		Browse
:start				:en_gb		Start
:iterative			:en_gb		Iterative
:final				:en_gb		Final
:run				:en_gb		Run
:help				:en_gb		Help
:quit				:en_gb		Quit
:ready				:en_gb		Ready
:running			:en_gb		Running...
:source_path_not_entred		:en_gb		Please select a valid Source Path.
:dest_path_not_entred		:en_gb		Please select a valid Destination Path.
:interrupted			:en_gb		Interrupted
:completed			:en_gb		Completed
:error_occurred			:en_gb		Error Occurred
:confirm_to_compress		:en_gb		Hot Compression can't store the changes made during the compression, Do you want to continue ? 
:ok				:en_gb		Ok
:cancel				:en_gb		Cancel

:confirm_to_compress_online	:en_gb		Confirm to compress Database Online.





