---
apiVersion: v1
kind: Pod
metadata:
  name: tilecacher-pod
  namespace: gss-prod
  labels:
    app: predix
spec:
  containers:
  - name: tilecacher-pod
    image: pull.dc-gisuat-webm1:30443/pwr-smallworld/tilecacher:latest
    command:
    - node
    - tilecacher.js
    - "-v"
    - "-d"
    - "/config"
    volumeMounts:
    - name: config-volume
      mountPath: /config
  imagePullSecrets:
  - name: regsecret
  volumes:
    - name: config-volume
      configMap:
        name: cm-tilecacher-config
