---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: gss-prod
  labels:
    app: predix
    service-cluster: bifrost
    service: rabbitmq
spec:
  type: ClusterIP
  ports:
  - port: 5672
    protocol: TCP
  selector:
    app: predix
    service-cluster: bifrost
    service: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-lb-deployment
  namespace: gss-prod
  labels:
    app: predix
    service-cluster: bifrost
    service: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predix
      service-cluster: bifrost
      service: rabbitmq
  template:
    metadata:
      labels:
        app: predix
        service-cluster: bifrost
        service: rabbitmq
    spec:
      hostname: load
      containers:
      - name: rabbitmq-lb-pod
        image: pull.dc-gisuat-webm1:30443/pwr-smallworld/rabbitmq:3.8.16-management-alpine_0.1.0
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: bifrost-rabbitmq-secret
              key: rabbitmqadmin
        - name: RABBITMQ_ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: bifrost-rabbitmq-secret
              key: rabbitmqadminsecret
        volumeMounts:
        - name: rabbitmq-lb-volume
          mountPath: /var/lib/rabbitmq
        lifecycle:
          preStop:
            exec:
              command: ["rabbitmqctl", "shutdown"]
      imagePullSecrets:
      - name: regsecret
      initContainers:
      - name: init-rabbitmq-permissions
        image: pull.dc-gisuat-webm1:30443/pwr-smallworld/alpine:3.12.0
        command:
        - chown
        - -R
        - 1001:1001
        - /var/lib/rabbitmq
        volumeMounts:
          - name: rabbitmq-lb-volume
            mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-lb-volume
        persistentVolumeClaim:
          claimName: nfs-storage-class-bifrost-rabbitmq-gss-prod-pvc
