id: 'bsf-ingress-controller'
api_version: '5.3.0'
targets:
  - id: 'ingress-controller'
    products:
      - id: 'pdi-ingress-controller'
        # Configure local_dir_mount_path to point to directory holding kube config
        local_dir_mount_path: '/osds_data/sw_gss_deploy/local/'
        pdi:
          image: 'dtr.predix.io/pwr-smallworld/pdi-ingress-controller-eks'
          tag: '1.0.1'
        param_groups:
          - id: 'environment'
            params:
              KUBECONFIG: '/data/local/kubeconfig/config'
              NAMESPACE: 'ingress-controller'
              ## Uncomment and set for aws deployment
              # AWS_CA_BUNDLE: ''
              # AWS_PROFILE: ''
              # AWS_REGION: ''
              # http_proxy: ''
              # https_proxy: ''
              # no_proxy: ''
          - id: 'values-ingress'
            params:
              imagePullSecrets:
              - name: regsecret
              controller:
                admissionWebhooks:
                  enabled: false
                image:
                  repository: 'dtr.predix.io/pwr-smallworld/nginx-ingress-controller'
                  tag: '0.41.2'
                service:
                  enableHttp: false
                  targetPorts:
                    http: http
                    https: http
                  type: NodePort
                  nodePorts:
                    https: '30443'
                  annotations:
                    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:822584052713:certificate/d5eb506b-53c1-5c1f-8c12-2ae327cab382
                    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
                    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
                    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
                config:
                  use-proxy-protocol: "false"
                  use-forwarded-headers: "true"
                  proxy-real-ip-cidr: "0.0.0.0/0" # restrict this to the IP addresses of ALB
                  proxy-body-size: '2m'
                  # # Uncomment for GISA for ADMS Series 3 deployments
                  # ssl-ciphers: 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384'
                  # ssl-protocols: 'TLSv1.2'
              defaultBackend:
                image:
                  repository: 'dtr.predix.io/pwr-smallworld/defaultbackend'
                  tag: '1.5'
