#% text_encoding = iso8859_1

:mig_tool_view_readonly		  :en_gb	'#1' dataset view readonly. Please make it writable.
:mig_tool_excel_file_not_entered  :en_gb	Directory:'#1'. Please select a valid Excel File Path.
:mig_tool_log_dir_not_entered     :en_gb        Directory:'#1'.Please select a log directory
:mig_tool_file_not_found	  :en_gb	File:'#1' not found in the selected directory:'#2'.
:mig_tool_engine_running	  :en_gb	The migration import process is in progress.#nPlease interrupt the engine before you close the application.
:mig_tool_invalid_dataset_name	  :en_gb	Invalid dataset name:'#1' mentioned in the mapping file.
:mig_tool_invalid_collection_name :en_gb	Invalid SW mapping collection name:'#1'  mentioned.
:mig_tool_invalid_field_name	  :en_gb	Invalid SW field name:'#1' for the SW Table name:'#2'.
:mig_tool_mandatory_field	  :en_gb	No value given for Mandatory Field: #1 for Object: #2.
:mig_tool_record_exists           :en_gb	 Record already exists 
:mig_tool_invalid_table_name	  :en_gb	NO table is mapped in:'#1' .
