#% text_encoding = iso8859_1
:tool_name			:en_gb		Bulk Update Tool
:import_data			:en_gb		Update Data
:insert_data			:en_gb		Insert Data
:interrupt			:en_gb		Interrupt
:quit				:en_gb		Quit
:excel_folder_browse		:en_gb		Browse
:log_directory_browse		:en_gb		Browse
:update				:en_gb		Update
:insert				:en_gb		Insert
:excel_file_folder		:en_gb		Excel File Path
:log_directory_folder		:en_gb		Log Directory Path
:ready				:en_gb		Ready
:running			:en_gb		Running
:completed			:en_gb		Completed
:error_occurred			:en_gb		Error Occurred
:excel_file_not_entered         :en_gb          Please select a valid input Excel File Path.
:log_directory_not_entered      :en_gb          Please select a log directory.
:set_view_to_write_mode         :en_gb          Set the view to writable mode.
:interrupted			:en_gb		Interrupted






