#% text_encoding = iso8859_1

:status		        	   :en_gb	#1: #2/#3
:error			           :en_gb	[Error]: #1
:migration_log_message	           :en_gb	UPDATE INFORMATION
:start_time		           :en_gb	START TIME:
:end_time		           :en_gb	END TIME:
:sw_table_name_log_msg		   :en_gb       SW TABLE NAMES:
:hash				   :en_gb       #########################
:log_heading_key		   :en_gb       LOG - LOADING '#1'
:log_id				   :en_gb       UNIQUE ID
:log_error_description	           :en_gb       ERROR DESCRIPTION
:summary			   :en_gb	SUMMARY
:current_object_cnt		   :en_gb	Total Number of Records Processed
:total_row_count		   :en_gb	Total Number of Records Present in the Input File
:error_object_cnt		   :en_gb	Total Number of Error Records
:successfully_inserted_object_cnt  :en_gb	Total Number of Records Inserted Successfully
:error_record                      :en_gb	Error Records
:excel_could_notbe_access	   :en_gb	The export engine could not get access to Microsoft Excel since it is currently busy.
:no_data_given_in_excel_sheet	   :en_gb	No data present in Excel sheet 
:file_open_state		   :en_gb	The operation cannot be performed when the input file is still open by other application. Please close the file and continue the process
:update_tool_invalid_dataset_name  :en_gb	Invalid dataset name: mentioned in the Input file.
:update_tool_invalid_field_name	   :en_gb	Invalid SW field name
:update_tool_invalid_field_value   :en_gb	Invalid field value : 
:update_tool_mandatory_field	   :en_gb	No value given for Mandatory Field
