kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-storage-class-solr-gss-prod-pvc
  namespace: gss-prod
spec:
  storageClassName: nfs-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi