kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-storage-class-elasticsearch-logging-pvc
  namespace: logging
spec:
  storageClassName: nfs-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi