#% text_encoding = iso8859_1
:tp_tpsodl_building_query	TPSODL Building
:tp_circle_query	Circle
:tp_division_query	Division
:lnd_subdivision_query	Subdivision
:lnd_section_query	Section
:lnd_zip_query	Zip
:tp_locality_boundary_query	Locality Boundary
:tp_sub_locality_query	Sub Locality
:tp_municipal_ward_boundary_query	Municipal Ward Boundary
:tp_village_boundary_query	Village Boundary
:tp_slum_area_query	Slum Area
:tp_environment_query	Environment
:tp_flood_map_query	Flood Map
:lnd_waterbody_query	Waterbody
:lnd_wetland_query	Wetland
:tp_estate_land_type_query	Estate Land Type
:tp_cluster_of_trees_query	Cluster of Trees
:tp_tree_query	Tree
:tp_transit_area_query	Transit Area
:tp_vehicle_demarcated_boundary_query	Vehicle Demarcated Boundary
:lnd_railroad_query	Railroad
:lnd_street_query	Road
:lnd_street_segment_query	Road Centerline
:tp_footpath_query	Footpath
:tp_right_of_way_query	Right of Way
:tp_obstacle_query	Obstacle
:tp_utility_points_query	Utility Points
:tp_telecom_query	Telecom
:lnd_restricted_area_query	Restricted Area
:lnd_landmark_query	Landmark
:tp_non_builtup_query	Non Builtup
:tp_builtup_query	Builtup
:tp_gate_query	Gate
:tp_green_query	Green
:tp_shop_query	Shop
:tp_tpsodl_boundary_query	TPSODL Boundary
:lnd_building_query	Building
:ed_cabinet_query	Cabinet
:eo_cable_segment_inst_query	Cable Segment
:eo_circuit_query	Circuit
:eo_comms_device_query	Comms Device
:eo_conduit_query	Conduit
:eo_connector_point_inst_query	Connector Point Installation
:eo_connector_segment_inst_query	Connector Segment Installation
:ed_decorative_pole_query	Decorative Pole
:eo_energy_source_query	Energy Source
:eo_energy_storage_inst_query	Energy Storage Installation
:eo_fiber_optic_query	Fiber Optic
:eo_isolating_eqpt_inst_query	Isolating Equipment Installation
:eo_measuring_eqpt_inst_query	Measuring Equipment Installation
:eo_meter_query	Meter
:ed_pole_query	Pole
:eo_power_xfrmr_inst_query	Power Transformer Installation
:eo_protective_eqpt_inst_query	Protective Equipment Installation
:eo_service_connection_query	Service Connection
:eo_service_point_query	Service Point
:sub_substation_query	Substation
:ed_switchgear_query	Switchgear
:et_tower_query	Tower
:eo_wire_segment_inst_query	Wire Segment