:spat_pre_tool	Spatial Predicate Tool
:src_obj_type	Source Object Type
:dest_obj_type	Destination Object Type
:trail	Trail
:map_view	Map View
:map_selection	Map Selection
:all	All
:source_object_files	Source Object Files
:fixed_cluster	Fixed Cluster
:variable_cluster	Variable Cluster
:cluster_selection	Cluster Selection
:source_object_fields	Source Object Fields
:destination_object_fields	Destination Object Fields
:electric			Electric
:land				Land
:both				Both
:dataset			Dataset
:operation_type			Operation Type
:within				Within
:interacts			Interacts
:overlays			Overlays
:overlaps			Overlaps
:src_obj_fld_value		Source object field value only
:obj_outside_src_obj		Object outside source object
:buffer				Buffer
:shortest_path			Shortest Path
:shortest_path_ext_file		Shortest Path(External File)		
:press_cntrl_for_selection	Press Ctrl for selecting multiple fields value in Source/Destination fields
:add_remarks			Additional Remarks
:max_chars			Max 20 Characters
:reset				Reset
:export_to_explorer		Export to Explorer
:quit				Quit
:src_sel_type			Source Selection Type
:src_obj_flds			Source Object Fields
:reports_fields_for_join_reports       Reports Fields For Join Reports      
:in_mtrs			       In Mtrs.			       
:interupt			Interupt
:get_report			Get Report
:dst_obj_flds			Destination Object Fields
:rpt_fld_jn_rpt			Reports Fields For Join Reports
:src_sel_typ			Source Selection Type
