---
apiVersion: v1
kind: Service
metadata:
  name: tpsodl-eo-web-service
  namespace: gss-prod
  labels:
    app: predix
    service-cluster: load-balancer
    service: tpsodl-eo-web
spec:
  type: ClusterIP
  ports:
  - port: 7771
    protocol: TCP
  selector:
    app: predix
    service-cluster: load-balancer
    service: tpsodl-eo-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpsodl-eo-web-deployment
  namespace: gss-prod
  labels:
    app: predix
    service-cluster: load-balancer
    service: tpsodl-eo-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predix
      service-cluster: load-balancer
      service: tpsodl-eo-web
  template:
    metadata:
      labels:
        app: predix
        service-cluster: load-balancer
        service: tpsodl-eo-web
    spec:
      hostAliases:
      - ip: "192.168.200.91"
        hostnames:
        - "dc-gisuat-webm1"
      - ip: "192.168.200.86"
        hostnames:
        - "dc-gisuat-webw2"
      - ip: "192.168.200.88"
        hostnames:
        - "dc-gisuat-webl2"
      - ip: "192.168.200.43"
        hostnames:
        - "dc-gisdev-db02"
        - "dc-gisdev-db02.tpsodlcorp.tpsodl.com"
      containers:
      - name: tpsodl-eo-web-pod
        image: pull.dc-gisuat-webm1:30443/pwr-smallworld/tpsodl-eo-web:SW528-PROD-2
        ports:
        - containerPort: 7771
        env:
        - name: SW_ACE_DB_DIR
          value: dc-gisdev-db02:/f$/LCC_DB/gis_db_lcc/ds_admin
        - name: SW_MODELIT_DB_DIR
          value: 
        - name: SW_MESSAGE_DB_DIR
          value: dc-gisdev-db02:/f$/smallworld_registry
        - name: SW_DB_CONTEXT_DIR
          value: 
        - name: SW_ALIAS_LOCATION
          value: /Smallworld/tpsodl_eo/TPSODLElectricOfficeWeb/config/gis_aliases
        - name: SW_GIS_ALIAS
          value: tpsodl_eo_web_vertx_open
        - name: SW_APPLICATION_NAME
          value: tpsodl_eo_web_vertx_server_application
        - name: SW_LANGUAGE
          value: en_gb
        - name: EIS_RESOURCES_PATH
          value: /eis_srv_resources
        - name: BIFROST_URL
          value: https://dc-gisuat-webm1:30443
        - name: GSS_LOGGING_LEVEL
          value: info
        - name: K8SHOST
          value: dc-gisuat-webm1
        - name: STSHOST
          value: dc-gisuat-webm1  
        - name: RABBIT_CONFIG_MODULE_NAME
          value: gss_basic_vertx_application
        - name: RABBIT_CONFIG_FILE_NAME
          value: empty_rabbit_config.xml
        - name: RABBITMQ_PATH
          valueFrom:
            secretKeyRef:
              name: bifrost-rabbitmq-secret
              key: path
        - name: MAGIK_SESSION_USER_NAME
          valueFrom:
            secretKeyRef:
              name: magik-user-secret
              key: username
        - name: MAGIK_SESSION_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: magik-user-secret
              key: password
        - name: TEMP
          value: /eis_logs
        - name: SOLR_HOST_NAME
          value: solr-service
        - name: SW_SOLR_USER
          valueFrom:
            secretKeyRef:
              name: solr-secret
              key: user
        - name: SW_SOLR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: solr-secret
              key: password
        - name: GSS_RESOURCE_KEY
          valueFrom:
            secretKeyRef:
              name: gss-resource-secret
              key: key
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SW_GISA_DEFAULT_CONFIG_NAME
          value: 
        - name: SW_GISA_DEFAULT_SOURCE_SYSTEM
          value: 
        livenessProbe:
          httpGet:
            path: /agent/status
            port: 7771
          periodSeconds: 60
          timeoutSeconds: 120
          initialDelaySeconds: 1200
        readinessProbe:
          httpGet:
            path: /agent/status
            port: 7771
          failureThreshold: 120
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: eis-config-volume
          mountPath: /Smallworld/tpsodl_eo/TPSODLElectricOfficeWeb/modules/tpsodl_eo_web_vertx_server_application/resources/base/data
        - name: eis-resources-volume
          mountPath: /eis_srv_resources
          subPath:  eis/resources
        - name: eis-resources-volume
          mountPath: /eis_logs
          subPath:  eis/logs
        - name: db-context-volume
          mountPath: /Smallworld/db_context/
        - name: eis-mount
          mountPath: /Smallworld/tpsodl_eo
        - name: eis-land-mount
          mountPath: /Smallworld/tp_cstm_product
      imagePullSecrets:
      - name: regsecret
      initContainers:
      - name: init-tpsodl-eo-web
        image: pull.dc-gisuat-webm1:30443/pwr-smallworld/alpine:3.12.0
        command:
        - chown
        - -R
        - 1000:0
        - /smallworld/
        volumeMounts:
        - name: eis-resources-volume
          mountPath: /smallworld/resources
          subPath: eis/resources
        - name: eis-resources-volume
          mountPath: /smallworld/logs
          subPath: eis/logs
      volumes:
      - name: eis-config-volume
        configMap:
          name: eis-config-cm
      - name: db-context-volume
        hostPath:
          path: /data/local/empty_dir
      - name: eis-resources-volume
        persistentVolumeClaim:
          claimName: nfs-storage-class-tpsodl-eo-web-gss-prod-pvc
      - name: eis-land-mount
        hostPath:
          path: /var/nfsshare/eis_product/tp_cstm_product
      - name: eis-mount
        hostPath:
          path: /var/nfsshare/eis_product/tpsodl_eo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpsodl-eo-web-async-deployment
  namespace: gss-prod
  labels:
    app: predix
    service-cluster: load-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predix
      service-cluster: load-balancer
  template:
    metadata:
      labels:
        app: predix
        service-cluster: load-balancer
    spec:
      hostAliases:
      - ip: "192.168.200.91"
        hostnames:
        - "dc-gisuat-webm1"
      - ip: "192.168.200.86"
        hostnames:
        - "dc-gisuat-webw2"
      - ip: "192.168.200.88"
        hostnames:
        - "dc-gisuat-webl2"
      - ip: "192.168.200.43"
        hostnames:
        - "dc-gisdev-db02"
        - "dc-gisdev-db02.tpsodlcorp.tpsodl.com"
      containers:
      - name: tpsodl-eo-web-async-pod
        image: pull.dc-gisuat-webm1:30443/pwr-smallworld/tpsodl-eo-web:SW528-PROD-2
        ports:
        - containerPort: 7771
        env:
        - name: SW_ACE_DB_DIR
          value: dc-gisdev-db02:/f$/LCC_DB/gis_db_lcc/ds_admin
        - name: SW_MODELIT_DB_DIR
          value: 
        - name: SW_MESSAGE_DB_DIR
          value: dc-gisdev-db02:/f$/smallworld_registry
        - name: SW_DB_CONTEXT_DIR
          value: 
        - name: SW_ALIAS_LOCATION
          value: /Smallworld/tpsodl_eo/TPSODLElectricOfficeWeb/config/gis_aliases
        - name: SW_GIS_ALIAS
          value: tpsodl_eo_web_vertx_open
        - name: SW_APPLICATION_NAME
          value: tpsodl_eo_web_vertx_server_application
        - name: SW_LANGUAGE
          value: en_gb
        - name: EIS_RESOURCES_PATH
          value: /eis_srv_resources
        - name: BIFROST_URL
          value: https://dc-gisuat-webm1:30443
        - name: GSS_LOGGING_LEVEL
          value: info
        - name: K8SHOST
          value: dc-gisuat-webm1
        - name: STSHOST
          value: dc-gisuat-webm1        
        - name: RABBIT_CONFIG_MODULE_NAME
          value: gss_basic_vertx_application
        - name: RABBIT_CONFIG_FILE_NAME
          value: rabbit_config.xml
        - name: RABBITMQ_PATH
          valueFrom:
            secretKeyRef:
              name: bifrost-rabbitmq-secret
              key: path
        - name: MAGIK_SESSION_USER_NAME
          valueFrom:
            secretKeyRef:
              name: magik-user-secret
              key: username
        - name: MAGIK_SESSION_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: magik-user-secret
              key: password
        - name: TEMP
          value: /eis_logs
        - name: SOLR_HOST_NAME
          value: solr-service
        - name: SW_SOLR_USER
          valueFrom:
            secretKeyRef:
              name: solr-secret
              key: user
        - name: SW_SOLR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: solr-secret
              key: password
        - name: GSS_RESOURCE_KEY
          valueFrom:
            secretKeyRef:
              name: gss-resource-secret
              key: key
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SW_GISA_DEFAULT_CONFIG_NAME
          value: 
        - name: SW_GISA_DEFAULT_SOURCE_SYSTEM
          value: 
        livenessProbe:
          httpGet:
            path: /agent/status
            port: 7771
          periodSeconds: 60
          timeoutSeconds: 120
          initialDelaySeconds: 1200
        readinessProbe:
          httpGet:
            path: /agent/status
            port: 7771
          failureThreshold: 120
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: eis-config-volume
          mountPath: /Smallworld/tpsodl_eo/TPSODLElectricOfficeWeb/modules/tpsodl_eo_web_vertx_server_application/resources/base/data
        - name: eis-resources-volume
          mountPath: /eis_srv_resources
          subPath:  eis/resources
        - name: eis-resources-volume
          mountPath: /eis_logs
          subPath:  eis/logs
        - name: db-context-volume
          mountPath: /Smallworld/db_context/
        - name: eis-mount
          mountPath: /Smallworld/tpsodl_eo
        - name: eis-land-mount
          mountPath: /Smallworld/tp_cstm_product
      imagePullSecrets:
      - name: regsecret
      initContainers:
      - name: init-tpsodl-eo-web
        image: pull.dc-gisuat-webm1:30443/pwr-smallworld/alpine:3.12.0
        command:
        - chown
        - -R
        - 1000:0
        - /smallworld/
        volumeMounts:
        - name: eis-resources-volume
          mountPath: /smallworld/resources
          subPath: eis/resources
        - name: eis-resources-volume
          mountPath: /smallworld/logs
          subPath: eis/logs
      volumes:
      - name: eis-config-volume
        configMap:
          name: eis-config-cm
      - name: db-context-volume
        hostPath:
          path: /data/local/empty_dir
      - name: eis-resources-volume
        persistentVolumeClaim:
          claimName: nfs-storage-class-tpsodl-eo-web-gss-prod-pvc
      - name: eis-mount
        hostPath:
          path: /var/nfsshare/eis_product/tpsodl_eo
      - name: eis-land-mount
        hostPath:
          path: /var/nfsshare/eis_product/tp_cstm_product