---
apiVersion: v1
kind: Service
metadata:
  name: tpsodl-eo-web-sts-service
  namespace: gss-prod
  labels:
    app: predix
    service-cluster: load-balancer
    service: tpsodl-eo-web-sts
spec:
  type: NodePort
  ports:
  - port: 4000
    protocol: TCP
    nodePort: 30400
  selector:
    app: predix
    service-cluster: load-balancer
    service: tpsodl-eo-web-sts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpsodl-eo-web-sts-deployment
  namespace: gss-prod
  labels:
    app: predix
    service-cluster: load-balancer
    service: tpsodl-eo-web-sts
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: predix
      service-cluster: load-balancer
      service: tpsodl-eo-web-sts
  template:
    metadata:
      labels:
        app: predix
        service-cluster: load-balancer
        service: tpsodl-eo-web-sts
    spec:
      hostAliases:
      - ip: "192.168.200.91"
        hostnames:
        - "dc-gisuat-webm1"
      - ip: "192.168.200.86"
        hostnames:
        - "dc-gisuat-webw2"
      - ip: "192.168.200.88"
        hostnames:
        - "dc-gisuat-webl2"
      - ip: "192.168.200.43"
        hostnames:
        - "dc-gisdev-db02"
        - "dc-gisdev-db02.tpsodlcorp.tpsodl.com"
      containers:
      - name: tpsodl-eo-web-sts-deployment
        image: pull.dc-gisuat-webm1:30443/pwr-smallworld/tpsodl-eo-web:SW528-PROD-1
        command:
        - /bin/sh
        - /Smallworld/start-sts.sh
        ports:
        - name: sts-port 
          containerPort: 4000
        env:
        - name: SW_ACE_DB_DIR
          value: dc-gisdev-db02:/f$/TCS/gis_db/ds_admin
        - name: SW_MODELIT_DB_DIR
          value: 
        - name: SW_MESSAGE_DB_DIR
          value: dc-gisdev-db02:/f$/smallworld_registry
        - name: SW_DB_CONTEXT_DIR
          value: 
        - name: MAGIK_SESSION_USER_NAME
          valueFrom:
            secretKeyRef:
              name: magik-user-secret
              key: username
        - name: MAGIK_SESSION_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: magik-user-secret
              key: password
        - name: TEMP
          value: /eis_logs
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        livenessProbe:
          tcpSocket:
            port: sts-port
          periodSeconds: 60
          timeoutSeconds: 5
          initialDelaySeconds: 1200
        readinessProbe:
          tcpSocket:
            port: sts-port
          failureThreshold: 120
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: db-context-volume
          mountPath: /Smallworld/db_context/
        - name: eis-logs-volume
          mountPath: /eis_logs
          subPath:  eis/logs
      imagePullSecrets:
      - name: regsecret
      volumes:
        - name: db-context-volume
          hostPath:
            path: /data/local/empty_dir
        - name: eis-logs-volume
          persistentVolumeClaim:
            claimName: nfs-storage-class-tpsodl-eo-web-gss-prod-pvc
