---
apiVersion: v1
kind: Service
metadata:
  name: gdal-service
  namespace: gss-prod
  labels:
    app: predix
    service-cluster: load-balancer
    service: gdal
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: predix
    service-cluster: load-balancer
    service: gdal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdal-deployment
  namespace: gss-prod
  labels:
    app: predix
    service-cluster: load-balancer
    service: gdal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predix
      service-cluster: load-balancer
      service: gdal
  template:
    metadata:
      labels:
        app: predix
        service-cluster: load-balancer
        service: gdal
    spec:
      containers:
      - name: gdal-pod
        image: pull.dc-gisuat-webm1:30443/pwr-smallworld/gdalserver:1.3.0
        securityContext:
          runAsUser: 1001
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regsecret 
